from . import sale_order
from . import stock_picking
from . import account_move
from . import purchase_order
from . import product_template
from . import res_config_settings
from . import stock_quant
from . import mail_mail
from . import product_quality
from . import stock_move
from . import sale_damage_item
from . import res_company
from . import res_partner
from . import picking_type
