from . import product_template
from . import magneto_product_product
from . import sale_order
from . import magento_instance
from . import magento_import_export_ept
from . import magento_res_partner_ept
from . import magento_financial_status_ept
from . import order_queue_line
from . import sale_workflow_process
from . import product_queue_line
from . import magneto_product_template